### ISSUE TITLE
Code improvement idea: ArgParse

### ISSUE THREAD

**Issue by AntoninLoubiere** [ThaaoBlues/pmanager#1]
You could use: [argparse](https://docs.python.org/3/library/argparse.html#module-argparse), available in the default python (from version 3.2).
It will be more simple to use and more flexible for the user. And the help will be automatically generated.

You could use [sub commands](https://docs.python.org/3/library/argparse.html#sub-commands) to add all your command.
It could be a thing like:
```python
parser = argparse.ArgumentParser(prog='pmanager')
subparsers = parser.add_subparsers(help="The command to do")

projects_parser = subparsers.add_parser("projects", help="List all projects")
projects_parser.set_defaults(func=show_projects.show_projects)

new_parser = subparsers.add_parser("new", help="Add a new project")
new_parser.add_argument("modules", help="Modules to import in the project", nargs="*")
new_parser.set_defaults(func=new.new) # function to do

args = parser.parse_args(sys.argv[1:])
args.func(args)
```

**Comment by ThaaoBlues** [comment]
Issue fixed in the lastest commit, thanks for your good help :D
